version: '3'
services:
  mongo:
    image: mongo:3.2
    command: --auth
    restart: always
    ports:
    - "27017:27017"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    restart: always
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"