vault:
  host: "http://192.168.50.11:8200"
  key: "gexrt"
  decryptEndpoint: "v1/transit/decrypt"
  encryptEndpoint: "v1/transit/encrypt"
  token: "ef1054f3-076f-6869-4c77-84286e9d1ace"
  fields:
    - /name
    - /surname
    - /items/0
    - /items2/*
    - /address/street
    - /address/city/items/*/raw
    - /address/city/items/0/raw2
    - /address/city/name